import type { IconType } from "react-icons";
import {
  FaBehance,
  FaDiscord,
  FaFacebook,
  FaGithub,
  FaGoogle,
  FaInstagram,
  FaLinkedin,
  FaPinterest,
  FaReddit,
  FaTelegram,
  FaThreads,
  FaWhatsapp,
  FaX,
  FaXTwitter,
} from "react-icons/fa6";
import {
  HiArrowRight,
  HiArrowRightOnRectangle,
  HiArrowTopRightOnSquare,
  HiArrowUpRight,
  HiCalendarDays,
  HiEnvelope,
  HiOutlineArrowDownTray,
  HiOutlineArrowPath,
  HiOutlineArrowsRightLeft,
  HiOutlineBell,
  HiOutlineBriefcase,
  HiOutlineCheckCircle,
  HiOutlineCodeBracket,
  HiOutlineCog8Tooth,
  HiOutlineCreditCard,
  HiOutlineDocument,
  HiOutlineExclamationTriangle,
  HiOutlineShieldCheck,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineFilm,
  HiOutlineFolder,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineHeart,
  HiOutlineInformationCircle,
  HiOutlineLink,
  HiOutlineMagnifyingGlass,
  HiOutlineMapPin,
  HiOutlineMinus,
  HiOutlineMusicalNote,
  HiOutlinePaintBrush,
  HiOutlinePaperClip,
  HiOutlinePencilSquare,
  HiOutlinePlus,
  HiOutlinePuzzlePiece,
  HiOutlineQuestionMarkCircle,
  HiOutlineRocketLaunch,
  HiOutlineSparkles,
  HiOutlineSquares2X2,
  HiOutlineTrash,
  HiOutlineUserGroup,
  HiOutlineWindow,
  HiOutlineXCircle,
} from "react-icons/hi2";
import {
  PiBookBookmarkDuotone,
  PiCameraDuotone,
  PiGridFourDuotone,
  PiHouseDuotone,
  PiImageDuotone,
  PiImagesDuotone,
  PiLinkDuotone,
  PiShapes,
  PiSmileyDuotone,
  PiTextBDuotone,
  PiTextItalicDuotone,
  PiTextStrikethroughDuotone,
  PiTextUnderlineDuotone,
  PiUserCircleDuotone,
} from "react-icons/pi";
import { SiFigma, SiJavascript, SiNextdotjs, SiSupabase } from "react-icons/si";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  film: HiOutlineFilm,
  sparkles: HiOutlineSparkles,
  paintBrush: HiOutlinePaintBrush,
  userGroup: HiOutlineUserGroup,
  codeBracket: HiOutlineCodeBracket,
  briefcase: HiOutlineBriefcase,
  infoCircle: HiOutlineInformationCircle,
  creditCard: HiOutlineCreditCard,
  search: HiOutlineMagnifyingGlass,
  settings: HiOutlineCog8Tooth,
  logOut: HiArrowRightOnRectangle,
  heart: HiOutlineHeart,
  mockup: HiOutlineWindow,
  plugin: HiOutlinePuzzlePiece,
  download: HiOutlineArrowDownTray,
  plus: HiOutlinePlus,
  mapPin: HiOutlineMapPin,
  edit: HiOutlinePencilSquare,
  refreshCw: HiOutlineArrowPath,
  helpCircle: HiOutlineQuestionMarkCircle,
  folder: HiOutlineFolder,
  attach: HiOutlinePaperClip,
  compare: HiOutlineArrowsRightLeft,
  carousel: HiOutlineSquares2X2,
  audio: HiOutlineMusicalNote,
  trash: HiOutlineTrash,
  bell: HiOutlineBell,
  check: HiOutlineCheckCircle,
  shield: HiOutlineShieldCheck,
  // Icono que el componente Feedback busca para variant="warning"
  warning: HiOutlineExclamationTriangle,
  xCircle: HiOutlineXCircle,
  divider: HiOutlineMinus,
  bold: PiTextBDuotone,
  italic: PiTextItalicDuotone,
  underline: PiTextUnderlineDuotone,
  strikethrough: PiTextStrikethroughDuotone,
  link: PiLinkDuotone,
  emoji: PiSmileyDuotone,
  images: PiImagesDuotone,
  camera: PiCameraDuotone,
  shapes: PiShapes,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  google: FaGoogle,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  behance: FaBehance,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
