import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiOutlineFilm,
  HiOutlineSparkles,
  HiOutlinePaintBrush,
  HiOutlineUserGroup,
  HiOutlineCodeBracket,
  HiOutlineBriefcase,
  HiOutlineInformationCircle,
  HiOutlineCreditCard,
  HiOutlineMagnifyingGlass,
  HiOutlineCog8Tooth,
  HiArrowRightOnRectangle,
  HiOutlineHeart,
  HiOutlineWindow,
  HiOutlinePuzzlePiece,
  HiOutlineArrowDownTray,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiImagesDuotone,
  PiCameraDuotone,
  PiShapes,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, FaGoogle, FaApple, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  film: HiOutlineFilm,
  sparkles: HiOutlineSparkles,
  paintBrush: HiOutlinePaintBrush,
  userGroup: HiOutlineUserGroup,
  codeBracket: HiOutlineCodeBracket,
  briefcase: HiOutlineBriefcase,
  infoCircle: HiOutlineInformationCircle,
  creditCard: HiOutlineCreditCard,
  search: HiOutlineMagnifyingGlass,
  settings: HiOutlineCog8Tooth,
  logOut: HiArrowRightOnRectangle,
  heart: HiOutlineHeart,
  mockup: HiOutlineWindow,
  plugin: HiOutlinePuzzlePiece,
  download: HiOutlineArrowDownTray,
  images: PiImagesDuotone,
  camera: PiCameraDuotone,
  shapes: PiShapes,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  google: FaGoogle,
  apple: FaApple,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
