import type { IconType } from "react-icons";
import {
  FaBehance,
  FaDiscord,
  FaFacebook,
  FaGithub,
  FaGoogle,
  FaInstagram,
  FaLinkedin,
  FaPinterest,
  FaReddit,
  FaTelegram,
  FaThreads,
  FaWhatsapp,
  FaX,
  FaXTwitter,
} from "react-icons/fa6";
import {
  HiArrowRight,
  HiArrowRightOnRectangle,
  HiArrowTopRightOnSquare,
  HiArrowUpRight,
  HiCalendarDays,
  HiEnvelope,
  HiOutlineArrowDownTray,
  HiOutlineArrowPath,
  HiOutlineArrowsRightLeft,
  HiOutlineBell,
  HiOutlineBriefcase,
  HiOutlineChatBubbleOvalLeftEllipsis,
  HiOutlineCheckCircle,
  HiOutlineCodeBracket,
  HiOutlineCog8Tooth,
  HiOutlineCreditCard,
  HiOutlineDocument,
  HiOutlineExclamationTriangle,
  HiOutlineShieldCheck,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineFilm,
  HiOutlineFolder,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineHeart,
  HiOutlineInformationCircle,
  HiOutlineLink,
  HiOutlineMagnifyingGlass,
  HiOutlineMapPin,
  HiOutlineMinus,
  HiOutlineMusicalNote,
  HiOutlinePaintBrush,
  HiOutlinePaperClip,
  HiOutlinePencilSquare,
  HiOutlinePhone,
  HiOutlinePlayCircle,
  HiOutlinePlus,
  HiOutlinePuzzlePiece,
  HiOutlineQuestionMarkCircle,
  HiOutlineRocketLaunch,
  HiOutlineSparkles,
  HiOutlineSquare2Stack,
  HiOutlineSquares2X2,
  HiOutlineTrash,
  HiOutlineUserGroup,
  HiOutlineVideoCamera,
  HiOutlineWindow,
  HiOutlineXCircle,
} from "react-icons/hi2";
import {
  PiBookBookmarkDuotone,
  PiCameraDuotone,
  PiDotsSixVerticalDuotone,
  PiDotsThreeVerticalBold,
  PiGridFourDuotone,
  PiHouseDuotone,
  PiImageDuotone,
  PiImagesDuotone,
  PiLinkDuotone,
  PiShapes,
  PiSmileyDuotone,
  PiTextAaBold,
  PiTextAaLight,
  PiTextAlignCenterDuotone,
  PiTextAlignJustifyDuotone,
  PiTextAlignLeftDuotone,
  PiTextAlignRightDuotone,
  PiTextBDuotone,
  PiTextItalicDuotone,
  PiTextStrikethroughDuotone,
  PiTextUnderlineDuotone,
  PiUserCircleDuotone,
} from "react-icons/pi";
import { SiFigma, SiJavascript, SiNextdotjs, SiSupabase } from "react-icons/si";
// Iconos de tipos de bloque del editor de contenido (ver ContentBlocks.tsx,
// BLOCK_TYPES/ALL_BLOCK_META): Tabler (Tb) para representar el RESULTADO
// visual real de cada bloque, no un objeto literal relacionado (ver
// auditoría "iconos coherentes"). `carouselSlides` = Carousel nativo de
// Once UI (un slide con flechas/indicador, ver mdx-carousel.tsx).
// `swipeStrip` = tira horizontal deslizable de chips (bloque "scroller").
import { TbCarouselHorizontal, TbSwipe } from "react-icons/tb";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  film: HiOutlineFilm,
  sparkles: HiOutlineSparkles,
  paintBrush: HiOutlinePaintBrush,
  userGroup: HiOutlineUserGroup,
  codeBracket: HiOutlineCodeBracket,
  briefcase: HiOutlineBriefcase,
  infoCircle: HiOutlineInformationCircle,
  creditCard: HiOutlineCreditCard,
  search: HiOutlineMagnifyingGlass,
  settings: HiOutlineCog8Tooth,
  logOut: HiArrowRightOnRectangle,
  heart: HiOutlineHeart,
  mockup: HiOutlineWindow,
  plugin: HiOutlinePuzzlePiece,
  download: HiOutlineArrowDownTray,
  plus: HiOutlinePlus,
  mapPin: HiOutlineMapPin,
  edit: HiOutlinePencilSquare,
  refreshCw: HiOutlineArrowPath,
  helpCircle: HiOutlineQuestionMarkCircle,
  folder: HiOutlineFolder,
  attach: HiOutlinePaperClip,
  compare: HiOutlineArrowsRightLeft,
  carousel: HiOutlineSquares2X2,
  audio: HiOutlineMusicalNote,
  trash: HiOutlineTrash,
  bell: HiOutlineBell,
  phone: HiOutlinePhone,
  video: HiOutlineVideoCamera,
  play: HiOutlinePlayCircle,
  chat: HiOutlineChatBubbleOvalLeftEllipsis,
  check: HiOutlineCheckCircle,
  shield: HiOutlineShieldCheck,
  // Icono que el componente Feedback busca para variant="warning"
  warning: HiOutlineExclamationTriangle,
  xCircle: HiOutlineXCircle,
  divider: HiOutlineMinus,
  // Bloque "Carousel" (mediaCarousel, Carousel nativo Once UI: un slide a la
  // vez con flechas + indicador).
  carouselSlides: TbCarouselHorizontal,
  // Bloque "Cuadrícula de fotos" (masonry, MasonryGrid real): grid 2x2, no
  // una sola foto (ver auditoría de iconos).
  photoGrid: HiOutlineSquares2X2,
  // Bloque "Tira de fotos" (carousel legacy, Scroller de imágenes apiladas
  // una tras otra): dos cuadros superpuestos = pila de fotos deslizable.
  photoStack: HiOutlineSquare2Stack,
  // Bloque "Tira deslizable" (scroller, chips en Scroller horizontal):
  // gesto de deslizar/swipe, no una sola flecha.
  swipeStrip: TbSwipe,
  bold: PiTextBDuotone,
  italic: PiTextItalicDuotone,
  underline: PiTextUnderlineDuotone,
  strikethrough: PiTextStrikethroughDuotone,
  textLight: PiTextAaLight,
  textStrong: PiTextAaBold,
  alignLeft: PiTextAlignLeftDuotone,
  alignCenter: PiTextAlignCenterDuotone,
  alignRight: PiTextAlignRightDuotone,
  alignJustify: PiTextAlignJustifyDuotone,
  link: PiLinkDuotone,
  emoji: PiSmileyDuotone,
  images: PiImagesDuotone,
  camera: PiCameraDuotone,
  shapes: PiShapes,
  dragHandle: PiDotsSixVerticalDuotone,
  moreVertical: PiDotsThreeVerticalBold,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  google: FaGoogle,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  behance: FaBehance,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
