"use client";

import { useMemo } from "react";
import { Button, Card, Column, MasonryGrid, Media, RevealFx, Row, Tag, Text, TiltFx } from "@once-ui-system/core";
import { ALL_APPS, ALL_FORMATS, ALL_ORIENTATIONS, useResourceSearch } from "./SearchContext";

const ALL = "Todos";

// Datos ilustrativos: aún no existe una librería real de recursos en la plataforma.
// Usa todas las imágenes disponibles en /public/images para probar la vista con más densidad de contenido.
const MOCK_RESOURCES = [
  {
    id: "resource-01",
    title: "Mockup de presentación 1",
    category: "Mockups",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Figma",
    image: "/images/avatar-01.jpg",
    downloads: 80,
  },
  {
    id: "resource-02",
    title: "Plugin para Photoshop 1",
    category: "Plug-ins",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Photoshop",
    image: "/images/avatar.jpg",
    downloads: 127,
  },
  {
    id: "resource-03",
    title: "Ilustración vectorial 1",
    category: "Imágenes",
    format: "JPG",
    orientation: "Horizontal",
    app: "Illustrator",
    image: "/images/blog/02/libro-huevon.jpg",
    downloads: 174,
  },
  {
    id: "resource-04",
    title: "Fotografía de stock 1",
    category: "Fotos",
    format: "PNG",
    orientation: "Horizontal",
    app: "After Effects",
    image: "/images/blog/03/image-01.png",
    downloads: 221,
  },
  {
    id: "resource-05",
    title: "Set de iconos 1",
    category: "Iconos",
    format: "PNG",
    orientation: "Horizontal",
    app: "Sketch",
    image: "/images/blog/03/image-02.png",
    downloads: 268,
  },
  {
    id: "resource-06",
    title: "Mockup de presentación 2",
    category: "Mockups",
    format: "PNG",
    orientation: "Horizontal",
    app: "Adobe XD",
    image: "/images/blog/03/image-03.png",
    downloads: 315,
  },
  {
    id: "resource-07",
    title: "Plugin para Blender 2",
    category: "Plug-ins",
    format: "PNG",
    orientation: "Horizontal",
    app: "Blender",
    image: "/images/blog/03/image-04.png",
    downloads: 362,
  },
  {
    id: "resource-08",
    title: "Ilustración vectorial 2",
    category: "Imágenes",
    format: "JPG",
    orientation: "Horizontal",
    app: "Figma",
    image: "/images/blog/03/image-06.jpeg",
    downloads: 409,
  },
  {
    id: "resource-09",
    title: "Fotografía de stock 2",
    category: "Fotos",
    format: "PNG",
    orientation: "Horizontal",
    app: "Photoshop",
    image: "/images/blog/04/img_01.png",
    downloads: 456,
  },
  {
    id: "resource-10",
    title: "Set de iconos 2",
    category: "Iconos",
    format: "PNG",
    orientation: "Horizontal",
    app: "Illustrator",
    image: "/images/blog/04/img_02.png",
    downloads: 503,
  },
  {
    id: "resource-11",
    title: "Mockup de presentación 3",
    category: "Mockups",
    format: "PNG",
    orientation: "Horizontal",
    app: "After Effects",
    image: "/images/blog/05/img_01.png",
    downloads: 550,
  },
  {
    id: "resource-12",
    title: "Plugin para Sketch 3",
    category: "Plug-ins",
    format: "PNG",
    orientation: "Horizontal",
    app: "Sketch",
    image: "/images/blog/05/img_02.png",
    downloads: 597,
  },
  {
    id: "resource-13",
    title: "Ilustración vectorial 3",
    category: "Imágenes",
    format: "PNG",
    orientation: "Cuadrada",
    app: "Adobe XD",
    image: "/images/blog/05/img_03.png",
    downloads: 644,
  },
  {
    id: "resource-14",
    title: "Fotografía de stock 3",
    category: "Fotos",
    format: "PNG",
    orientation: "Horizontal",
    app: "Blender",
    image: "/images/cover.png",
    downloads: 691,
  },
  {
    id: "resource-15",
    title: "Set de iconos 3",
    category: "Iconos",
    format: "PNG",
    orientation: "Vertical",
    app: "Figma",
    image: "/images/gallery/News/img-16.png",
    downloads: 738,
  },
  {
    id: "resource-16",
    title: "Mockup de presentación 4",
    category: "Mockups",
    format: "PNG",
    orientation: "Vertical",
    app: "Photoshop",
    image: "/images/gallery/News/img-17.png",
    downloads: 785,
  },
  {
    id: "resource-17",
    title: "Plugin para Illustrator 4",
    category: "Plug-ins",
    format: "PNG",
    orientation: "Vertical",
    app: "Illustrator",
    image: "/images/gallery/News/img-18.png",
    downloads: 832,
  },
  {
    id: "resource-18",
    title: "Ilustración vectorial 4",
    category: "Imágenes",
    format: "PNG",
    orientation: "Vertical",
    app: "After Effects",
    image: "/images/gallery/News/img-19.png",
    downloads: 879,
  },
  {
    id: "resource-19",
    title: "Fotografía de stock 4",
    category: "Fotos",
    format: "PNG",
    orientation: "Vertical",
    app: "Sketch",
    image: "/images/gallery/News/img-20.png",
    downloads: 926,
  },
  {
    id: "resource-20",
    title: "Set de iconos 4",
    category: "Iconos",
    format: "PNG",
    orientation: "Vertical",
    app: "Adobe XD",
    image: "/images/gallery/News/img-21.png",
    downloads: 123,
  },
  {
    id: "resource-21",
    title: "Mockup de presentación 5",
    category: "Mockups",
    format: "JPG",
    orientation: "Vertical",
    app: "Blender",
    image: "/images/gallery/img-01.jpg",
    downloads: 170,
  },
  {
    id: "resource-22",
    title: "Plugin para Figma 5",
    category: "Plug-ins",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Figma",
    image: "/images/gallery/img-02.jpg",
    downloads: 217,
  },
  {
    id: "resource-23",
    title: "Ilustración vectorial 5",
    category: "Imágenes",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Photoshop",
    image: "/images/gallery/img-03.jpg",
    downloads: 264,
  },
  {
    id: "resource-24",
    title: "Fotografía de stock 5",
    category: "Fotos",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Illustrator",
    image: "/images/gallery/img-04.jpg",
    downloads: 311,
  },
  {
    id: "resource-25",
    title: "Set de iconos 5",
    category: "Iconos",
    format: "JPG",
    orientation: "Cuadrada",
    app: "After Effects",
    image: "/images/gallery/img-05.jpg",
    downloads: 358,
  },
  {
    id: "resource-26",
    title: "Mockup de presentación 6",
    category: "Mockups",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Sketch",
    image: "/images/gallery/img-06.jpg",
    downloads: 405,
  },
  {
    id: "resource-27",
    title: "Plugin para Adobe XD 6",
    category: "Plug-ins",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Adobe XD",
    image: "/images/gallery/img-07.jpg",
    downloads: 452,
  },
  {
    id: "resource-28",
    title: "Ilustración vectorial 6",
    category: "Imágenes",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Blender",
    image: "/images/gallery/img-08.jpg",
    downloads: 499,
  },
  {
    id: "resource-29",
    title: "Fotografía de stock 6",
    category: "Fotos",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Figma",
    image: "/images/gallery/img-09.jpg",
    downloads: 546,
  },
  {
    id: "resource-30",
    title: "Set de iconos 6",
    category: "Iconos",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Photoshop",
    image: "/images/gallery/img-10.jpg",
    downloads: 593,
  },
  {
    id: "resource-31",
    title: "Mockup de presentación 7",
    category: "Mockups",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Illustrator",
    image: "/images/gallery/img-11.jpg",
    downloads: 640,
  },
  {
    id: "resource-32",
    title: "Plugin para After Effects 7",
    category: "Plug-ins",
    format: "JPG",
    orientation: "Cuadrada",
    app: "After Effects",
    image: "/images/gallery/img-12.jpg",
    downloads: 687,
  },
  {
    id: "resource-33",
    title: "Ilustración vectorial 7",
    category: "Imágenes",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Sketch",
    image: "/images/gallery/img-13.jpg",
    downloads: 734,
  },
  {
    id: "resource-34",
    title: "Fotografía de stock 7",
    category: "Fotos",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Adobe XD",
    image: "/images/gallery/img-14.jpg",
    downloads: 781,
  },
  {
    id: "resource-35",
    title: "Set de iconos 7",
    category: "Iconos",
    format: "JPG",
    orientation: "Vertical",
    app: "Blender",
    image: "/images/gallery/img-15.jpg",
    downloads: 828,
  },
  {
    id: "resource-36",
    title: "Mockup de presentación 8",
    category: "Mockups",
    format: "JPG",
    orientation: "Vertical",
    app: "Figma",
    image: "/images/gallery/img-16.jpg",
    downloads: 875,
  },
  {
    id: "resource-37",
    title: "Plugin para Photoshop 8",
    category: "Plug-ins",
    format: "JPG",
    orientation: "Vertical",
    app: "Photoshop",
    image: "/images/gallery/img-17.jpg",
    downloads: 922,
  },
  {
    id: "resource-38",
    title: "Ilustración vectorial 8",
    category: "Imágenes",
    format: "JPG",
    orientation: "Vertical",
    app: "Illustrator",
    image: "/images/gallery/img-18.jpg",
    downloads: 119,
  },
  {
    id: "resource-39",
    title: "Fotografía de stock 8",
    category: "Fotos",
    format: "JPG",
    orientation: "Vertical",
    app: "After Effects",
    image: "/images/gallery/img-19.jpg",
    downloads: 166,
  },
  {
    id: "resource-40",
    title: "Set de iconos 8",
    category: "Iconos",
    format: "JPG",
    orientation: "Vertical",
    app: "Sketch",
    image: "/images/gallery/img-20.jpg",
    downloads: 213,
  },
  {
    id: "resource-41",
    title: "Mockup de presentación 9",
    category: "Mockups",
    format: "JPG",
    orientation: "Vertical",
    app: "Adobe XD",
    image: "/images/gallery/img-21.jpg",
    downloads: 260,
  },
  {
    id: "resource-42",
    title: "Plugin para Blender 9",
    category: "Plug-ins",
    format: "PNG",
    orientation: "Cuadrada",
    app: "Blender",
    image: "/images/projects/project-01/avatar-01.png",
    downloads: 307,
  },
  {
    id: "resource-43",
    title: "Ilustración vectorial 9",
    category: "Imágenes",
    format: "PNG",
    orientation: "Cuadrada",
    app: "Figma",
    image: "/images/projects/project-01/avatar-02.png",
    downloads: 354,
  },
  {
    id: "resource-44",
    title: "Fotografía de stock 9",
    category: "Fotos",
    format: "PNG",
    orientation: "Cuadrada",
    app: "Photoshop",
    image: "/images/projects/project-01/avatar-03.png",
    downloads: 401,
  },
  {
    id: "resource-45",
    title: "Set de iconos 9",
    category: "Iconos",
    format: "PNG",
    orientation: "Cuadrada",
    app: "Illustrator",
    image: "/images/projects/project-01/avatar-04.png",
    downloads: 448,
  },
  {
    id: "resource-46",
    title: "Mockup de presentación 10",
    category: "Mockups",
    format: "PNG",
    orientation: "Cuadrada",
    app: "After Effects",
    image: "/images/projects/project-01/avatar-05.png",
    downloads: 495,
  },
  {
    id: "resource-47",
    title: "Plugin para Sketch 10",
    category: "Plug-ins",
    format: "JPG",
    orientation: "Horizontal",
    app: "Sketch",
    image: "/images/projects/project-01/cover-01.jpg",
    downloads: 542,
  },
  {
    id: "resource-48",
    title: "Ilustración vectorial 10",
    category: "Imágenes",
    format: "JPG",
    orientation: "Horizontal",
    app: "Adobe XD",
    image: "/images/projects/project-01/cover-02.jpg",
    downloads: 589,
  },
  {
    id: "resource-49",
    title: "Fotografía de stock 10",
    category: "Fotos",
    format: "JPG",
    orientation: "Horizontal",
    app: "Blender",
    image: "/images/projects/project-01/cover-03.jpg",
    downloads: 636,
  },
  {
    id: "resource-50",
    title: "Set de iconos 10",
    category: "Iconos",
    format: "JPG",
    orientation: "Horizontal",
    app: "Figma",
    image: "/images/projects/project-01/cover-04.jpg",
    downloads: 683,
  },
  {
    id: "resource-51",
    title: "Mockup de presentación 11",
    category: "Mockups",
    format: "JPG",
    orientation: "Horizontal",
    app: "Photoshop",
    image: "/images/projects/project-01/image-01.jpg",
    downloads: 730,
  },
  {
    id: "resource-52",
    title: "Plugin para Illustrator 11",
    category: "Plug-ins",
    format: "JPG",
    orientation: "Horizontal",
    app: "Illustrator",
    image: "/images/projects/project-01/image-02.jpg",
    downloads: 777,
  },
  {
    id: "resource-53",
    title: "Ilustración vectorial 11",
    category: "Imágenes",
    format: "JPG",
    orientation: "Horizontal",
    app: "After Effects",
    image: "/images/projects/project-01/image-03.jpg",
    downloads: 824,
  },
  {
    id: "resource-54",
    title: "Fotografía de stock 11",
    category: "Fotos",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Sketch",
    image: "/images/projects/project-Helvex/img-01.jpg",
    downloads: 871,
  },
  {
    id: "resource-55",
    title: "Set de iconos 11",
    category: "Iconos",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Adobe XD",
    image: "/images/projects/project-Helvex/img-02.jpg",
    downloads: 918,
  },
  {
    id: "resource-56",
    title: "Mockup de presentación 12",
    category: "Mockups",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Blender",
    image: "/images/projects/project-Helvex/img-03.jpg",
    downloads: 115,
  },
  {
    id: "resource-57",
    title: "Plugin para Figma 12",
    category: "Plug-ins",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Figma",
    image: "/images/projects/project-Helvex/img-04.jpg",
    downloads: 162,
  },
  {
    id: "resource-58",
    title: "Ilustración vectorial 12",
    category: "Imágenes",
    format: "PNG",
    orientation: "Horizontal",
    app: "Photoshop",
    image: "/images/projects/project-NBA/cover-01.png",
    downloads: 209,
  },
  {
    id: "resource-59",
    title: "Fotografía de stock 12",
    category: "Fotos",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Illustrator",
    image: "/images/projects/project-nba-cup-2025/Andres-01.jpg",
    downloads: 256,
  },
  {
    id: "resource-60",
    title: "Set de iconos 12",
    category: "Iconos",
    format: "PNG",
    orientation: "Cuadrada",
    app: "After Effects",
    image: "/images/projects/project-nba-cup-2025/Armando-01.png",
    downloads: 303,
  },
  {
    id: "resource-61",
    title: "Mockup de presentación 13",
    category: "Mockups",
    format: "JPG",
    orientation: "Cuadrada",
    app: "Sketch",
    image: "/images/projects/project-nba-cup-2025/Julian-01.jpg",
    downloads: 350,
  },
  {
    id: "resource-62",
    title: "Plugin para Adobe XD 13",
    category: "Plug-ins",
    format: "PNG",
    orientation: "Horizontal",
    app: "Adobe XD",
    image: "/images/projects/project-nba-cup-2025/still-01.png",
    downloads: 397,
  },
  {
    id: "resource-63",
    title: "Ilustración vectorial 13",
    category: "Imágenes",
    format: "JPG",
    orientation: "Horizontal",
    app: "Blender",
    image: "/images/projects/project-nba-style/Cover-01.jpg",
    downloads: 444,
  },
  {
    id: "resource-64",
    title: "Fotografía de stock 13",
    category: "Fotos",
    format: "JPG",
    orientation: "Vertical",
    app: "Figma",
    image: "/images/projects/project-nba-style/Rodrigo-01.jpg",
    downloads: 491,
  },
  {
    id: "resource-65",
    title: "Set de iconos 13",
    category: "Iconos",
    format: "JPG",
    orientation: "Horizontal",
    app: "Photoshop",
    image: "/images/projects/project-nba-style/img-01.jpg",
    downloads: 538,
  },
  {
    id: "resource-66",
    title: "Mockup de presentación 14",
    category: "Mockups",
    format: "JPG",
    orientation: "Horizontal",
    app: "Illustrator",
    image: "/images/projects/project-nba-style/img-02.jpg",
    downloads: 585,
  },
];

function ResourceCard({ resource }: { resource: (typeof MOCK_RESOURCES)[number] }) {
  return (
    <TiltFx fillWidth radius="l">
      <Card fillWidth direction="column" radius="l" border="neutral-alpha-weak" background="neutral-alpha-weak">
        <Column fillWidth paddingX="8" paddingTop="8">
          <Media src={resource.image} alt={resource.title} radius="m" sizes="(max-width: 768px) 50vw, 25vw" />
        </Column>

        <Column fillWidth paddingX="12" paddingY="8" gap="4">
          <Row fillWidth horizontal="between" vertical="center" gap="8">
            <Text variant="label-strong-s" onBackground="neutral-strong" truncate>
              {resource.title}
            </Text>
            <Tag size="s" variant="brand" label={resource.format} style={{ flexShrink: 0 }} />
          </Row>
          <Text variant="body-default-xs" onBackground="neutral-weak">
            {resource.category}
          </Text>
        </Column>

        <Row fillWidth horizontal="between" vertical="center" paddingX="12" paddingBottom="8">
          <Button variant="tertiary" size="xs" prefixIcon="download">
            {resource.downloads}
          </Button>
        </Row>
      </Card>
    </TiltFx>
  );
}

interface ResourceFeedProps {
  initialCategory?: string;
}

export function ResourceFeed({ initialCategory }: ResourceFeedProps) {
  const selected = initialCategory ?? ALL;
  const { query, format, orientation, app } = useResourceSearch();

  const filtered = useMemo(
    () =>
      MOCK_RESOURCES.filter((resource) => {
        if (selected !== ALL && resource.category !== selected) return false;
        if (format !== ALL_FORMATS && resource.format !== format) return false;
        if (orientation !== ALL_ORIENTATIONS && resource.orientation !== orientation) return false;
        if (app !== ALL_APPS && resource.app !== app) return false;
        if (query && !resource.title.toLowerCase().includes(query.trim().toLowerCase())) return false;
        return true;
      }),
    [selected, format, orientation, app, query],
  );

  return (
    <RevealFx key={selected} fillWidth direction="column" gap="24" translateY="8" speed="fast">
      {filtered.length === 0 ? (
        <Text onBackground="neutral-weak" variant="body-default-m">
          No encontramos recursos que coincidan con tu búsqueda.
        </Text>
      ) : (
        <MasonryGrid columns={4} m={{ columns: 2 }} s={{ columns: 2 }} gap="16" fillWidth>
          {filtered.map((resource) => (
            <ResourceCard key={resource.id} resource={resource} />
          ))}
        </MasonryGrid>
      )}
    </RevealFx>
  );
}
